apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/puiterwijkinfra/testapp
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: testapp
    app.kubernetes.io/component: testapp
    app.kubernetes.io/instance: testapp
    app.kubernetes.io/name: testapp
    app.kubernetes.io/part-of: testapp-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi9
  name: testapp
spec:
  lookupPolicy:
    local: false
